In [9]:
import gym
import numpy as np
env =gym.make("FrozenLake-v1",is_slippery=True)

In [10]:
print("num_state ",env.observation_space)

print("num_action ",env.action_space)

num_state  Discrete(16)
num_action  Discrete(4)


In [11]:
env.reset()
for i in range(10000):
    random_act=env.action_space.sample()
    observation ,reward,termine,truncate,info =env.step(random_act)
    print(reward)
    print(f"Action : {random_act} , observation : {observation}, Reward : {reward}")
    done =termine
    if done : 
        break

0.0
Action : 1 , observation : 4, Reward : 0.0
0.0
Action : 2 , observation : 5, Reward : 0.0


F:\Anaconda\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


## Exercice 2 : Implementation de la Q-Table 

In [12]:
# Initialisation de la Q-Table
num_states = env.observation_space.n  # Nombre d’états
num_actions = env.action_space.n  # Nombre d’actions
q_table = np.zeros((num_states, num_actions))  # Q-Table remplie de zéros

print("Q-Table initialisée :")
print(q_table)

Q-Table initialisée :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
import random

alpha = 0.1  
gamma = 0.99  
epsilon = 1.0  
epsilon_decay = 0.995  
epsilon_min = 0.01  
episodes = 5000  


for episode in range(episodes):
    state = env.reset()[0]  
    done = False

    while not done:
        
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  
        else:
            action = np.argmax(q_table[state, :])  

        
        new_state, reward, done, _, _ = env.step(action)

        
        q_table[state, action] = (1 - alpha) * q_table[state, action] + \
                                 alpha * (reward + gamma * np.max(q_table[new_state, :]))

        state = new_state  

   
    epsilon = max(epsilon * epsilon_decay, epsilon_min)

print("Entraînement terminé !")
print("Q-Table finale :")
print(q_table)


Entraînement terminé !
Q-Table finale :
[[5.59373852e-01 4.08213919e-01 4.69019010e-01 4.22028411e-01]
 [6.26606999e-03 2.61771709e-01 3.46558348e-03 9.42114614e-02]
 [3.38242105e-01 3.52084942e-02 3.32138905e-02 5.14079799e-02]
 [0.00000000e+00 3.73881452e-02 0.00000000e+00 1.99053345e-06]
 [5.86733027e-01 3.69476141e-01 3.36715693e-01 3.65586232e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.28089546e-01 9.16317070e-02 2.55783332e-01 1.99589551e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.12018066e-01 4.80457477e-01 3.57866599e-01 6.52568915e-01]
 [3.97025011e-01 6.90996519e-01 3.98376968e-01 4.13830582e-01]
 [6.42801905e-01 4.03297718e-01 3.90773926e-01 2.61187627e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.83090918e-01 4.48308853e-01 8.08283581e-01 5.74273780e-01]
 [5.67893308e-01 9.24447066e-01 6.97974670e-01 7.59411208e-01]
 [0.00000000e+0

In [14]:
state = env.reset()[0]
done = False
env.render()

while not done:
    action = np.argmax(q_table[state, :])  
    new_state, reward, done, _, _ = env.step(action)
    env.render() 
    state = new_state

print("Test terminé !")


Test terminé !


F:\Anaconda\Lib\site-packages\gym\envs\toy_text\frozen_lake.py:271: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("FrozenLake-v1", render_mode="rgb_array")
  logger.warn(


In [15]:
num_tests = 100  # 
success_count = 0  

for _ in range(num_tests):
    state = env.reset()[0]  
    done = False

    while not done:
        action = np.argmax(q_table[state, :])  
        new_state, reward, done, _, _ = env.step(action)
        state = new_state  

        if done and reward == 1:  
            success_count += 1

print(f" L'agent a atteint l'objectif {success_count} fois sur {num_tests} épisodes.")
print(f"Taux de réussite : {success_count / num_tests * 100:.2f}%")

🎯 L'agent a atteint l'objectif 74 fois sur 100 épisodes.
🔥 Taux de réussite : 74.00%


In [7]:
print(count)

0
